### ISSUE TITLE
Backend data is not visible on application

### ISSUE THREAD

**Issue by whitehack2512** [spiffe/spire-tutorials#39]
Hi Team,

I have set up all the files and pods are running successfully, the points which I want to clarify are listed below :

1) I can not expose my application via external ip due to some restriction, in this case whether it will work or not ?
2) I am able to access my frontend applications as of now with http://workerip:port but in this scenario data is not appearing on the application.

files for envoy configuration for all backend & frontend applications are correct.

Please suggest as early as possible.

[snapshot_spire.docx](https://github.com/spiffe/spire-tutorials/files/5182075/snapshot_spire.docx)

**Comment by whitehack2512** [comment]
Can this work with node port configuration without using ingress ?

**Comment by Andres-GC** [comment]
Hi whitehack251,

From the snapshots you shared I see that you are able to load the frontend app on your browser so I think the issue is with the connection to the backend service.

Assuming you are following the Envoy-X509 tutorial, did you create the registration entries on SPIRE to let Envoy establish the TLS connection between the frontend and the backend? This is the step: https://github.com/spiffe/spire-tutorials/tree/master/k8s/envoy-x509#create-registration-entries

Another thing I would check is the logs from Envoy. Check if it is able to get a certificate from SPIRE via the SDS module.

Regards.

**Comment by whitehack2512** [comment]
Hi Andres,

Issue has been resolved, I figure out for the connections and re-run the cluster and now it is working fine, I expose them with the help of nodeport.
